[package]
name = "kagi"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
input = "0.8.2"
libc = "0.2.146"
tokio = { version = "1.28.2", features = ["full"]}
